services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart-retail-app
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - retail-network

networks:
  retail-network:
    driver: bridge
